// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa_AQaVm_L44IShUhzfozBPKPQ6BasqRY',
    appId: '1:311581291504:web:0f5a3467bcf85533f56335',
    messagingSenderId: '311581291504',
    projectId: 'finalproject-77e4a',
    authDomain: 'finalproject-77e4a.firebaseapp.com',
    storageBucket: 'finalproject-77e4a.firebasestorage.app',
    measurementId: 'G-DQRCYZBQN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgI0XFlWC9rRDnY0uh0jX3bGi6CtKlkTw',
    appId: '1:311581291504:android:79c794b90aec5b79f56335',
    messagingSenderId: '311581291504',
    projectId: 'finalproject-77e4a',
    storageBucket: 'finalproject-77e4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDoJpL9saiLUjwgcUm90Buf17d6miyVXE',
    appId: '1:311581291504:ios:1edc2c55287794daf56335',
    messagingSenderId: '311581291504',
    projectId: 'finalproject-77e4a',
    storageBucket: 'finalproject-77e4a.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDoJpL9saiLUjwgcUm90Buf17d6miyVXE',
    appId: '1:311581291504:ios:1edc2c55287794daf56335',
    messagingSenderId: '311581291504',
    projectId: 'finalproject-77e4a',
    storageBucket: 'finalproject-77e4a.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa_AQaVm_L44IShUhzfozBPKPQ6BasqRY',
    appId: '1:311581291504:web:9e2cb7ec9b7805fff56335',
    messagingSenderId: '311581291504',
    projectId: 'finalproject-77e4a',
    authDomain: 'finalproject-77e4a.firebaseapp.com',
    storageBucket: 'finalproject-77e4a.firebasestorage.app',
    measurementId: 'G-RWDRZDQSX3',
  );

}